# Generated by Django 4.2.7 on 2025-12-02 12:18

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_deliverycouriers_url_parameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to=userauths.models.user_directory_path
            ),
        ),
    ]
