# Generated by Django 4.2.7 on 2025-12-02 12:18

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0003_user_reset_token_alter_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default/default-user.jpg",
                null=True,
                upload_to=userauths.models.user_directory_path,
            ),
        ),
    ]
